[project]
name = "tslearn-for-time-series-analysis-with-python"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.0",
    "pytest>=8.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "scikit-learn>=1.8.0",
    "tslearn>=0.8.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
